<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="Resources\Fonts\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Resources\Fonts\**" />
    <None Remove="Models\**" />
    <None Remove="Resources\Fonts\**" />
    <Page Remove="Models\**" />
    <Page Remove="Resources\Fonts\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
    <Content Remove="C:\Users\juan.parvol\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net10.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Images\montacargas_hp_der.png" />
    <None Remove="Resources\Images\montacargas_hp_izq.png" />
    <None Remove="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\montacargas_hp_der.png" />
    <Resource Include="Resources\Images\montacargas_hp_izq.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Articulos\ViewModels\" />
    <Folder Include="Features\Auditar\ViewModels\" />
    <Folder Include="Features\CheckList\ViewModels\" />
    <Folder Include="Features\ControlPatio\ViewModels\" />
    <Folder Include="Features\DashBoard\ViewModels\" />
    <Folder Include="Features\InventarioAleatorio\ViewModels\" />
    <Folder Include="Features\Inventario\ViewModels\" />
    <Folder Include="Features\Movimientos\ViewModels\" />
    <Folder Include="Features\Reportes\ViewModels\" />
    <Folder Include="Features\Shared\ViewModels\" />
    <Folder Include="Services\" />


    <Folder Include="Resources\Fonts\" />
    <Folder Include="Resources\Styles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LD.Client\LD.Client.csproj" />
    <ProjectReference Include="..\LD.Contracts\LD.Contracts.csproj" />
  </ItemGroup>

</Project>
