<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>MauiAppLogin</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Enable XAML source generation for faster build times and improved performance.
		     This generates C# code from XAML at compile time instead of runtime inflation.
		     To disable, remove this line.
		     For individual files, you can override by setting Inflator metadata:
		       <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
		       <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<!-- Display name -->
		<ApplicationTitle>MauiAppLogin</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.mauiapplogin</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\logo.png" Color="#1F3A5F" BaseSize="268,158" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
	  <AndroidResource Remove="Platforms\Android\Resources\xml\XMLFile1.xml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="8.*" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="7.1.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.41" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
		<PackageReference Include="Plugin.Maui.OCR" Version="1.1.1" />
		<PackageReference Include="Refractored.MvvmHelpers" Version="1.6.2" />
		<PackageReference Include="ZXing.Net.Maui" Version="0.7.4" />
		<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.7.4" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LD.Client\LD.Client.csproj" />
	  <ProjectReference Include="..\LD.Contracts\LD.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Features\Seguridad\Views\RegisterLicense.xaml.cs">
		<DependentUpon>RegisterLicense.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Features\Controls\Card.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Almacenista\Views\ChangeLocationPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Almacenista\Views\PickingPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Almacenista\Views\ReceptionPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Seguridad\Views\RegisterVehicule.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Seguridad\Views\RegisterLicense.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Seguridad\Views\SignatureDriver.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Consultas\Views\MovementPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Consultas\Views\MovementDetail.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\ReporteDanos\Views\DamageReportPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\ReporteDanos\Views\DamageReportDetailPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\ReporteDanos\Views\DamageReportPrintPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Operaciones\Views\WarehouseOperations.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Inventario\Views\InventoryList.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Checklist\Views\ForkliftChecklistPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Tareas\Views\TaskList.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Tareas\Views\TaskSecurity.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Tareas\Views\NewTask.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Tareas\Views\TaskResolve.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Scanning\Views\Scan3FieldsPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Scanning\Views\ScanStandarLD.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Dashboard\Views\DashboardPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Auth\Views\LoginPage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\HomePage.xaml">
		<Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
