using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Collections;
using System.Data;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace LD.FormsX.Helpers
{
    public sealed class DataGridColumnFilterManager
    {
        private readonly DataGrid _dataGrid;
        private readonly Dictionary<string, string> _filters = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, bool?> _booleanFilters = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, object?> _originalHeaders = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, Border> _filterBorders = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, TextBox> _filterTextBoxes = new(StringComparer.OrdinalIgnoreCase);
        private Style? _stretchHeaderStyle;
        private ICollectionView? _collectionView;
        private Predicate<object>? _baseFilter;
        private bool _filtersVisible;

        public DataGridColumnFilterManager(DataGrid dataGrid)
        {
            _dataGrid = dataGrid;
            _dataGrid.Loaded += (_, _) => RefreshHeaders();
            _dataGrid.AutoGeneratedColumns += (_, _) => RefreshHeaders();
            _dataGrid.PreviewKeyDown += DataGrid_PreviewKeyDown;
            EnsureExportContextMenu();
        }

        public void ApplyTo(ICollectionView? collectionView)
        {
            if (collectionView == null)
                return;

            _collectionView = collectionView;
            _baseFilter = collectionView.Filter;
            collectionView.Filter = CombinedFilter;
            RefreshHeaders();
            collectionView.Refresh();
        }

        public void Clear()
        {
            _filters.Clear();
            _booleanFilters.Clear();
            RefreshHeaders();
            _collectionView?.Refresh();
        }

        private bool CombinedFilter(object obj)
        {
            if (_baseFilter != null && !_baseFilter(obj))
                return false;

            foreach (var filter in _filters)
            {
                if (!MatchesFilter(obj, filter.Key, filter.Value))
                    return false;
            }

            foreach (var filter in _booleanFilters)
            {
                if (!MatchesBooleanFilter(obj, filter.Key, filter.Value))
                    return false;
            }

            return true;
        }

        private bool MatchesFilter(object item, string propertyPath, string filterText)
        {
            var value = GetPropertyValue(item, propertyPath);
            var text = Convert.ToString(value, CultureInfo.CurrentCulture) ?? string.Empty;
            return !string.IsNullOrWhiteSpace(text)
                && text.IndexOf(filterText, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static bool MatchesBooleanFilter(object item, string propertyPath, bool? filterValue)
        {
            if (!filterValue.HasValue)
                return true;

            var value = GetPropertyValue(item, propertyPath);
            if (value is bool boolValue)
                return boolValue == filterValue.Value;

            return false;
        }

        private static object? GetPropertyValue(object item, string propertyPath)
        {
            if (item is DataRowView rowView)
            {
                var column = rowView.Row.Table.Columns
                    .Cast<DataColumn>()
                    .FirstOrDefault(c => string.Equals(c.ColumnName, propertyPath, StringComparison.OrdinalIgnoreCase));

                if (column != null)
                    return rowView[column.ColumnName];

                return null;
            }

            if (item is IDictionary<string, object?> genericDictionary
                && genericDictionary.TryGetValue(propertyPath, out var genericValue))
            {
                return genericValue;
            }

            if (item is IDictionary dictionary && dictionary.Contains(propertyPath))
                return dictionary[propertyPath];

            object? current = item;

            foreach (var segment in propertyPath.Split('.'))
            {
                if (current == null)
                    return null;

                var property = current.GetType().GetProperty(segment, BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
                if (property == null)
                    return null;

                current = property.GetValue(current);
            }

            return current;
        }

        private void RefreshHeaders()
        {
            _filterBorders.Clear();
            _filterTextBoxes.Clear();

            foreach (var column in _dataGrid.Columns)
            {
                var propertyPath = GetPropertyPath(column);
                if (string.IsNullOrWhiteSpace(propertyPath))
                    continue;

                if (!_originalHeaders.ContainsKey(propertyPath))
                    _originalHeaders[propertyPath] = column.Header;

                column.Header = BuildHeader(
                    propertyPath,
                    _originalHeaders[propertyPath]?.ToString() ?? propertyPath,
                    column is DataGridCheckBoxColumn);
                column.HeaderStyle = GetStretchHeaderStyle();
            }

            _dataGrid.ColumnHeaderHeight = _filtersVisible ? 52 : 26;
            UpdateVisualStates();
        }

        private FrameworkElement BuildHeader(string propertyPath, string title, bool isBooleanColumn)
        {
            var headerPanel = new Grid
            {
                ToolTip = $"Filtrar por {title}",
                HorizontalAlignment = HorizontalAlignment.Stretch,
                Margin = new Thickness(-4, 0, -4, 0)
            };

            var titleBlock = new TextBlock
            {
                Text = title,
                FontWeight = FontWeights.SemiBold,
                Foreground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#16263D")),
                Margin = _filtersVisible
                    ? new Thickness(6, 0, 6, 26)
                    : new Thickness(6, 0, 6, 0),
                VerticalAlignment = VerticalAlignment.Top,
                TextTrimming = TextTrimming.CharacterEllipsis
            };
            headerPanel.Children.Add(titleBlock);

            var filterBorder = new Border
            {
                CornerRadius = new CornerRadius(2),
                BorderThickness = new Thickness(0),
                Padding = isBooleanColumn ? new Thickness(0) : new Thickness(4, 0, 4, 0),
                Height = 28,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Bottom,
                Margin = new Thickness(6, 0, 6, 2),
                MinWidth = 0,
                Visibility = _filtersVisible ? Visibility.Visible : Visibility.Collapsed,
                Background = isBooleanColumn
                    ? Brushes.Transparent
                    : new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FCFDFF"))
            };

            FrameworkElement filterControl;

            if (isBooleanColumn)
            {
                var filterCheckBox = new CheckBox
                {
                    IsThreeState = true,
                    IsChecked = _booleanFilters.TryGetValue(propertyPath, out var boolValue) ? boolValue : null,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    VerticalAlignment = VerticalAlignment.Bottom,
                    ToolTip = $"Filtrar por {title}"
                };

                filterCheckBox.Checked += (_, _) =>
                {
                    _booleanFilters[propertyPath] = true;
                    UpdateVisualStates();
                    _collectionView?.Refresh();
                };

                filterCheckBox.Unchecked += (_, _) =>
                {
                    _booleanFilters[propertyPath] = false;
                    UpdateVisualStates();
                    _collectionView?.Refresh();
                };

                filterCheckBox.Indeterminate += (_, _) =>
                {
                    _booleanFilters.Remove(propertyPath);
                    UpdateVisualStates();
                    _collectionView?.Refresh();
                };

                filterControl = filterCheckBox;
            }
            else
            {
                var filterTextBox = new TextBox
                {
                    Text = _filters.TryGetValue(propertyPath, out var value) ? value : string.Empty,
                    BorderThickness = new Thickness(0),
                    Background = Brushes.Transparent,
                    Foreground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#223247")),
                    CaretBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#2563EB")),
                    FontSize = 11,
                    Padding = new Thickness(0),
                    Margin = new Thickness(0),
                    VerticalContentAlignment = VerticalAlignment.Center,
                    HorizontalAlignment = HorizontalAlignment.Stretch,
                    HorizontalContentAlignment = HorizontalAlignment.Left,
                    ToolTip = $"Escribe para filtrar {title}"
                };

                filterTextBox.PreviewKeyDown += DataGrid_PreviewKeyDown;
                filterTextBox.TextChanged += (_, _) =>
                {
                    var text = filterTextBox.Text?.Trim() ?? string.Empty;
                    if (string.IsNullOrWhiteSpace(text))
                        _filters.Remove(propertyPath);
                    else
                        _filters[propertyPath] = text;

                    UpdateVisualStates();
                    _collectionView?.Refresh();
                };

                _filterTextBoxes[propertyPath] = filterTextBox;
                filterControl = filterTextBox;
            }

            filterBorder.Child = filterControl;
            headerPanel.Children.Add(filterBorder);
            _filterBorders[propertyPath] = filterBorder;

            return headerPanel;
        }

        private void UpdateVisualStates()
        {
            var activeBorderBrush = Brushes.Transparent;
            var activeBackground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FFF9DE"));
            var inactiveBorderBrush = Brushes.Transparent;
            var inactiveBackground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FCFDFF"));

            foreach (var border in _filterBorders)
            {
                var isActive = _filters.ContainsKey(border.Key) || _booleanFilters.ContainsKey(border.Key);
                border.Value.BorderBrush = isActive ? activeBorderBrush : inactiveBorderBrush;
                if (border.Value.Child is CheckBox)
                    border.Value.Background = Brushes.Transparent;
                else
                    border.Value.Background = isActive ? activeBackground : inactiveBackground;
            }
        }

        private Style GetStretchHeaderStyle()
        {
            if (_stretchHeaderStyle != null)
                return _stretchHeaderStyle;

            var baseStyle =
                _dataGrid.ColumnHeaderStyle
                ?? _dataGrid.TryFindResource(typeof(DataGridColumnHeader)) as Style;

            var style = new Style(typeof(DataGridColumnHeader), baseStyle);
            style.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Stretch));
            style.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Stretch));
            style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(4, 2, 4, 2)));

            _stretchHeaderStyle = style;
            return style;
        }

        private void DataGrid_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (Keyboard.Modifiers != ModifierKeys.Control)
                return;

            if (e.Key == Key.F)
            {
                e.Handled = true;
                ToggleFilters();
                return;
            }

            if (e.Key == Key.T)
            {
                e.Handled = true;
                ExportVisibleRows();
            }
        }

        private void ToggleFilters()
        {
            _filtersVisible = !_filtersVisible;
            RefreshHeaders();

            if (_filtersVisible)
                FocusFirstFilterTextBox();
            else
                _dataGrid.Focus();
        }

        private void FocusFirstFilterTextBox()
        {
            foreach (var textBox in _filterTextBoxes.Values)
            {
                textBox.Focus();
                textBox.SelectAll();
                break;
            }
        }

        private void EnsureExportContextMenu()
        {
            _dataGrid.ContextMenu ??= new ContextMenu();

            var existingExportItem = _dataGrid.ContextMenu.Items
                .OfType<MenuItem>()
                .FirstOrDefault(item => string.Equals(item.Name, "ExportToExcelMenuItem", StringComparison.Ordinal));

            if (existingExportItem != null)
                return;

            var exportItem = new MenuItem
            {
                Name = "ExportToExcelMenuItem",
                Header = "Exportar a Excel (Ctrl+T)"
            };
            exportItem.Click += (_, _) => ExportVisibleRows();

            _dataGrid.ContextMenu.Items.Add(exportItem);
        }

        private void ExportVisibleRows()
        {
            try
            {
                var filePath = _dataGrid.ExportVisibleRowsToExcel(_dataGrid.Name);
                ToastHelper.ShowInfo($"Archivo exportado correctamente:\n{filePath}", "Exportar a Excel");
            }
            catch (Exception ex)
            {
                DialogHelper.ShowWarning(ex.Message, "Exportar a Excel");
            }
        }

        private static string? GetPropertyPath(DataGridColumn column)
        {
            if (!string.IsNullOrWhiteSpace(column.SortMemberPath))
                return column.SortMemberPath;

            if (column is DataGridBoundColumn boundColumn &&
                boundColumn.Binding is Binding binding &&
                binding.Path != null &&
                !string.IsNullOrWhiteSpace(binding.Path.Path))
            {
                return binding.Path.Path;
            }

            return null;
        }
    }
}
