// <auto-generated />
using LD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LD.Infrastructure.Migrations
{
    [DbContext(typeof(LdProyectDbContext))]
    [Migration("20260614193000_AddSupplyStatusToKittingIssueDetails")]
    partial class AddSupplyStatusToKittingIssueDetails
    {
    }
}
