<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	 
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="X\**" />
    <EmbeddedResource Remove="X\**" />
    <None Remove="X\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LD.Contracts\LD.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Dialogs\FrmConfirm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevaUbicacionMasiva.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevaUbicacion.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevoArticuloMasiva.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevoArticulo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevoAlmacen.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevoProyecto.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmNuevoCliente.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmSuccess.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\FrmError.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmMovimientos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmArticulos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmUbicaciones.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmAlmacenes.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmProyectos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\FrmClientes.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

</Project>